######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 29 22:32:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
